### ISSUE TITLE
Request to add "Script Services" classes

### ISSUE THREAD

**Issue by jsavin** [almai/gas-docset#2]
I'm using the gas-docset to help learn Google Apps Script to implement some workflow automation, and noticed that the Browser class was missing. After a little digging, it appears that all of the classes documented under "Script Services" on Google's online docs are not included in the docset.

As an example, here are all of the Script Services > Base classes:
https://developers.google.com/apps-script/reference/base/

This is a request to please add them. :-)

Thanks!

**Comment by almai** [comment]
Yes you're right. This is "by design". Only the G-Suite Services are included in this docset. Script Services is worth another docset.

**Comment by jsavin** [comment]
I'd be happy to create/contribute one for Script Services. I attempted to generate a docset via HTML files downloaded from developers.google.com using `wget`, but wasn't successful with configuring the selectors in `dashing.json`. Did you do any preprocessing on Google's docs, and/or can you add instructions to `README.md` relating the method you used to generate the HTML files under the `gas` directory?
